restart
debug needsPackage "StringTorics"

topes = kreuzerSkarke(3, Limit => 1000);
  topes_15

Q = cyPolytopeData topes_15
  vertices polytope Q
  vertices polytope(Q, "M")
  vertices polytope(Q, "N")

methods makeCY
X = makeCY(Q, Ring => (RZ = ZZ[a,b,c]))
gens RZ

hh^(1,1) X
hh^(1,2) X

hh^(1,1) Q
hh^(1,2) Q
isFavorable Q

topologicalData X
intersectionNumbers X

c2 X -- second chern class of X (curve class)
 -- if picard group of X: generated by D0, D1, D2.
 -- c2(X) = C, get C.D0, C.D1, C.D2 integers
 
Xs = findAllCYs Q 
tops = Xs/topologicalData
netList tops
unique tops

X1 = Xs_0
topologicalData X1
X2 = Xs_1
topologicalData X2

F = cubicForm X
c2Form X
c2 X
intersectionNumbers X
X1.cache#"pic ring" = RZ
X2.cache#"pic ring" = RZ
c2 X1
toRingElement(c2 X1, RZ)

factor F
singF = ideal F + ideal jacobian F
singF = saturate(singF, ideal vars RZ)
ideal gens gb singF

invariants X1
invariants X2

gvInvariants(X1, DegreeLimit => 15)
rays gvCone(X1, DegreeLimit => 15)

gvInvariants(X2, DegreeLimit => 15)
rays gvCone(X2, DegreeLimit => 15)

gv1 = partitionGVConeByGV(X1, DegreeLimit => 15)
gv2 = partitionGVConeByGV(X2, DegreeLimit => 15)
findLinearMaps(gv1, gv2)
