doc ///
   Key
     StringTorics
   Headline
     toric variety functions useful for investigations in string theory
   Description
    Text
      This package uses the software packages TOPCOM, CohomCalg, and PALP, together
      with facilities already present in Macaulay2, to provide the following 
      functionality.
    Text
      @SUBSECTION "Routines to access the Kreuzer-Skarke database"@
    Text
      @UL {
          {TO "kreuzerSkarke"},
          {TO "kreuzerSkarkeDim3"}
          }@
    Text
      @SUBSECTION "Examples of use"@
    Text
      @UL {
          {TO "Example use", ", a first example showing basic usage of this package"}
          }@
    Text
      @SUBSECTION "Additional polyhedral functions"@
    Text
      @SUBSECTION "Triangulations"@
    Text
      @SUBSECTION "Cohomology"@
   Caveat
   SeeAlso
     "installing StringTorics"
///

-*
    Text
      @UL {
          {}
          }@

    Text
      @UL {
          {}
          }@
    Text
      @UL {
          {}
          }@
*-

doc ///
   Key
     "Example use"
   Headline
     An example of using the functionality of the package
   Description
    Text
      Let's analyze one particular toric variety, and the corresponding 
      Calabi-Yau hypersurface.

      First, take an example from the Kreuzer-Skarke database.  Note: you need to be online
      in order for this to work!
    Example
      polytopes = kreuzerSkarke(5, 57, Limit=>200, Access => "wget");
      #polytopes == 197
    Text
      There are 197 reflexive polytopes in 4 dimensions, whose
      (resolution of an) anti-canonical divisor X (a Calabi-Yau),
      has $h^{1,1}(X) = 5$, and $h^{1,2}(X) = 57$.
      
      Let's consider the 11th one on this list.
    Example
      polytopes_10
      A = matrix (polytopes_10)
    Text
      The Calabi-Yau is (the resolution of) an anti-canonical hypersurface
      in the 4 dimensional projective toric variety whose polytope is $P_1$
      in the $M$ lattice.
      
      This polytope has 10 vertices, 7 facets, and 56 lattice points: 
      the origin and 55 on the boundary.
    Example
      P1 = convexHull A
      fVector P1
      vertices P1
      matrix{latticePoints P1}

      # latticePointList P1
      vertexList P1
      transpose matrix latticePointList P1
    Text
      Now let's take the dual polytope (in the $N$-lattice)
    Example
      P2 = polar P1
    Text
      The following comand returns the list of non-zero lattice points, and
      the vertices appear first on this list.
    Example
      latticePointList P2
      transpose matrix latticePointList P2
      vertexMatrix P2
      V0 = normalToricVariety normalFan P1
      isSimplicial V0
      isSmooth V0
      V = reflexiveToSimplicialToricVariety P1
      isSimplicial V
      isSmooth V
      rays V == (latticePointList P2)_{0..#rays V-1}
    Text
      This is the simplicial toric variety we want!  Actually, any other
      simplicial toric variety will work too (i.e. any other fine star regular
      triangulation of the point configuration {\tt latticePointList P2}.
    Text
      The Calabi-Yau $X$ is an anti-canonical divisor in $V$ (the same as the
          pull-back of an anti-canonical divisor in $V_0$, which is ample, to $V$
          (the result is no longer ample).
      Batryev (based on Danilov-Khovanskii) has provided formulae for the Hodge numbers
      of such a hypersurface.  The formula for $h^{1,1}(X)$ and $h^{2,1}(X)$, for $X$ 
      the desingularization of a hypersurface in a Fano toric variety of dimension 4, 
      depends only on the polytope.
    Example
      h11OfCY P1
      h21OfCY P1
    Text
      The reflexive polytope is called favorable if $H^{1,1}(X)$ is generated by the
      images of toric divisors on $V$.
    Example
      isFavorable P1
    Text
      Intersection ring of $X$
    Text
      First, let's work on $X$, which is a sufficiently generic hypersurface of $V$
      in the divisor class $|-K_V|$.
    Example
      KV = toricDivisor V
      X = completeIntersection(V, {-KV})
    Text
      The Hodge diamond of $X$, as long as $X$ is sufficiently generic,
      is determined via Danilov-Khovanskii (reference: ...).  However, 
      the following works whenever $X$ is a smooth hypersurface of $V$.
    Example
      hodgeDiamond X
    Text
      Thus $h^{1,1}(X) = 5$ and $h^{1,2}(X) = 57$.
      
      We can do intersection theory on $X$ and $V$.  Note that $V$ is not smooth, but
      since it is simplicial, as long as we work over the rationals, not the integers,
      the intersection ring is well-defined.  Since $X$ is smooth (or assumed to be),
      the intersection ring of $X$ is well-defined.
      
      The way we do all of this is we first create the abstract variety of a point.
      We include some parameters here (we will use them below).  Then, we define
      abstract varieties for $V$ and $X$.  These are designed to work well with the
      intersection theory implemented in Macaulay2 (the package @TO "Schubert2"@).
      An abstract variety contains information about its intersection ring (or, the numerical
      intersection ring), the chern class of its tangent bundle, and how to integrate 
      a cycle on the variety.    
    Example
      pt = base(symbol a, symbol b, symbol c, symbol d, symbol e)
      Va = abstractVariety(V, pt)
      Xa = abstractVariety(X, pt)
      IX = intersectionRing Xa
    Text
      For example, the (restrictions to $X$) of the 9 toric prime divisors:
    Example
      gens IX
      integral(t_2*t_3*t_4)
      integral(t_2^3)
    Text
      The advantage of putting parameters into the base, is that we can generate
      formulas.  For example, the euler characteristic of $L = OO_X(aD_4+bD_5+cD_6+dD_7+eD_8)$
      ($L$ is a line bundle with the given element as first Chern class. Note
      that $D_4, \ldots, D_8$ generate the intersection ring) can be found using
      the following code, which invokes Hirzebruch-Riemann-Roch to find the euler
      characteristic.
    Example
      L = a*t_4 + b*t_5 + c*t_6 + d*t_7 + e*t_8
      F1 = chi OO(L)
      6*(F1-1)
   SeeAlso
///

doc ///
   Key
     hodgeOfCYToricDivisor
     (hodgeOfCYToricDivisor,Polyhedron,List)
   Headline
     compute the cohomology vector of an (irreducible) toric divisor on a CY hypersurface
   Usage
     hodgeOfCYToricDivisor(P,pt)
   Inputs
     P:Polyhedron
       Any polytope will do, although so far it has only been tested on 
       reflexive polytopes.
     pt:List
       a lattice point in the polar dual polytope {\tt polar P}
   Outputs
     :List
       The list of $\{ h^0(X,OO_D), h^1(X,OO_D), h^2(X,OO_D) \}$,
       where $D$ is the intersection of the toric divisor corresponding
       to the lattice point with a hypersurface $X$ corresponding to
       an anti-canonical divisor on the toric 4-fold $V$ corresoponding .
   Description
    Text
      We assume that $P$ is a reflexive 4-dimensional polytope, and let $V_0$ be the 4-dimensional
      toric variety corresponding to $P$ (i.e. corresponding to the normal fan of $P$).  Let $V$
      be a simplicial resolution of $V_0$, corresponding to a star triangulation of the polar dual
      $P^o$, which is fine, i.e. involves all of the lattice points of $P^o$.  Let $X \subset V$ be
      the inverse image of an anti-canonical divisor on $V_0$.  Note that from Batyrev, it turns
      out that $X$ is a smooth Calabi-Yau 3-fold.  Finally, a lattice point $pt$
      of $P^o$ corresponds to a toric divisor on $V$.  Let $D$ be the intersection of this divisor 
      with $X$.
      
      This function computes the vector of cohomologies of the structure sheaf of the surface $D$.
      
      As an example, the following example is taken from the Kreuzer-Skarke database of 4D reflexive 
      polytopes.
      
    Example
       polystr = "Kreuzer-Skarke: 4 12  M:24 12 N:16 11 H:11,19 [-16]
               1   0   0   0   0   1   2   1   0  -2   0  -2
               0   1   0   0   0   0  -2  -1   1   2  -1   0
               0   0   1   0   0  -1   0  -1  -1   1  -1   1
               0   0   0   1  -1   0   1   1  -1   0   1  -2
               "
      A = matrix first kreuzerSkarke polystr
      P = convexHull A
    Text
      This polytope has 12 vertices, 33 edges, 32 2-faces, and 11 facets.
    Example
      # faceList(0,P)
      # faceList(1,P)
      # faceList(2,P)
      # faceList(3,P)
      fVector P
    Text
      
      Note that only the faces which contain interior lattice points, or whose dual does, is included.
      So 6 of the 33 edges of the polytope have an interior vertex along that edge.
      
      There are 15 non-zero lattice points in the dual, meaning that the
      toric 4-fold has 15 toric divisors on it (each is a 3-fold, and also toric).
      It turn out that they all are rigid, in the sense that in each case,
      $h^0(OO_D) = 1$, $h^1(OO_D) = 0$, $h^2(OO_D) = 0$.
    Example
      # latticePointList polar P
      hodgeOfCYToricDivisors P
    Text
      The Hodge numbers $h^{1,1}(X)$ and $h^{2,1}(X)$ can be computed using 
      information about $P$ only, not the specific triangulation used.
    Example
      isFavorable P
      h11OfCY P
      h21OfCY P
   Caveat
     This function currently only works for 4-d reflexive polytopes.  However, the
     formulas work for other dimensions, and these should be included.
   SeeAlso
///

///
  Key
    vertexMatrix
  Headline
  Usage
  Inputs
  Outputs
  Consequences
  Description
    Text
    Example
  Caveat
  SeeAlso
///

///
-*
  restart
  needsPackage "StringTorics"
*-
  topes = kreuzerSkarke(5, Limit=>10, Access=>"wget")
  A = matrix topes_9
  P = convexHull A
  P2 = polar P
  LP = matrix{latticePoints P2}
  elems2 = regularSubdivision(LP, matrix{{1/2, 1/10, 10, 3, 2, 8, 12, 7/8, 9/11, 1}})
  hts = for i from 0 to numcols LP-1 list random 100
  elems3 = regularSubdivision(LP, matrix{hts})
  elems = regularFineTriangulation LP
  for e in elems list latticeVolume convexHull LP_e
  for e in elems2 list latticeVolume convexHull LP_e
  sum for e in elems3 list latticeVolume convexHull LP_e
  sort unique flatten elems == toList(0..numcols LP-1)
  sort unique flatten elems2 == toList(0..numcols LP-1)
  sort unique flatten elems3 == toList(0..numcols LP-1)
  -- I would like to check that these are well-defined triangulations
  sum oo
  latticeVolume P
  latticeVolume P2
  
  vertices P -- matrix over QQ
  vertexList P -- list (over ZZ or QQ?), different order than 'vertices'
  vertexMatrix P
  faceList
  faceDimensionHash
  minimalFace
  latticePoints P -- list of single column matrices, over ZZ
  latticePointList P
  latticePointHash
  interiorLatticePoints
  interiorLatticePointList
  faces(3,P)
  faceList(1,P)
  vertices P2
  matrix{latticePoints P2}
  
///

///
-*
  restart
  needsPackage "StringTorics"
*-
  topes = kreuzerSkarke(80, Limit=>10, Access=>"wget")
  A = matrix topes_9
  P = convexHull A
  P2 = polar P
  vertices P -- matrix over QQ
  vertexList P -- list (over ZZ or QQ?), different order than 'vertices'
  vertexMatrix P
  faceList
  faceDimensionHash
  minimalFace
  latticePoints P -- list of single column matrices, over ZZ
  latticePointList P
  latticePointHash
  interiorLatticePoints
  interiorLatticePointList
  faces(3,P)
  faceList(1,P)
  vertices P2
  matrix{latticePoints P2}
  
///

-*
///
  Key
  Headline
  Usage
  Inputs
  Outputs
  Consequences
  Description
    Text
    Example
  Caveat
  SeeAlso
///
*-

