doc ///
   Key
     StringTorics
   Headline
     toric variety functions useful for investigations in string theory
   Description
    Text
      This package uses the software packages TOPCOM, CohomCalg, and PALP, together
      with facilities already present in Macaulay2, to provide the following 
      functionality.
    Text
      @SUBSECTION "Examples of use"@
    Text
      @UL {
          {TO "Example use", ", a first example showing basic usage of this package"}
          }@
    Text
      @SUBSECTION "Routines to access the Kreuzer-Skarke database"@
    Text
      @UL {
          {TO "kreuzerSkarke"},
          {TO "kreuzerSkarkeDim3"}
          }@
    Text
      @SUBSECTION "Triangulations"@
    Text
      @UL {
          TO "facilities available for working with triangulations",
          TO regularFineStarTriangulation,
          TO allTriangulations,
          TO generateTriangulations
          }@
    Text
      @SUBSECTION "Creating and using CYDatabase's"@
      
      A CYDatabase is a file which contains precomputed data about a collection of
      (reflexive) 4D-polytopes and the resulting Calabi Yau hypersurfaces.
    Text
      @UL {
          TO createCYDatabase,
          TO addToCYDatabase,
          TO readCYDatabase,
          TO readCYPolytopes,
          TO readCYs
          }@
    Text
      @SUBSECTION "Cohomology"@
    Text
      @UL {
          TO "cohomology of line bundles on toric varieties",
          TO cohomologyVector,
          TO toricOrthants,
          TO cohomologyBasis,
          TO cohomologyMatrix,
          TO cohomologyMatrixRank
          }@
   Caveat
   SeeAlso
     "installing StringTorics"
///

-*
    Text
      @SUBSECTION "Additional polyhedral functions"@
    Text
      @UL {
          {}
          }@

    Text
      @UL {
          {}
          }@
    Text
      @UL {
          {}
          }@
*-

doc ///
   Key
     "Example use"
   Headline
     An example of using the functionality of the package
   Description
    Text
      Let's analyze one particular toric variety, and the corresponding 
      Calabi-Yau hypersurface.

      First, take an example from the Kreuzer-Skarke database.  Note: you need to be online
      in order for this to work!
    Example
      polytopes = kreuzerSkarke(5, 57, Limit=>200, Access => "wget");
      #polytopes == 197
    Text
      There are 197 reflexive polytopes in 4 dimensions, whose
      (resolution of an) anti-canonical divisor X (a Calabi-Yau),
      has $h^{1,1}(X) = 5$, and $h^{1,2}(X) = 57$.
      
      Let's consider the 11th one on this list.
    Example
      polytopes_10
      A = matrix (polytopes_10)
    Text
      The Calabi-Yau is (the resolution of) an anti-canonical hypersurface
      in the 4 dimensional projective toric variety whose polytope is $P_1$
      in the $M$ lattice.
      
      This polytope has 10 vertices, 7 facets, and 56 lattice points: 
      the origin and 55 on the boundary.
    Example
      P1 = convexHull A
      fVector P1
      vertices P1
      matrix{latticePoints P1}

      # latticePointList P1
      vertexList P1
      transpose matrix latticePointList P1
    Text
      Now let's take the dual polytope (in the $N$-lattice)
    Example
      P2 = polar P1
    Text
      The following comand returns the list of non-zero lattice points, and
      the vertices appear first on this list.
    Example
      latticePointList P2
      transpose matrix latticePointList P2
      vertexMatrix P2
      V0 = normalToricVariety normalFan P1
      isSimplicial V0
      isSmooth V0
      V = reflexiveToSimplicialToricVariety P1
      isSimplicial V
      isSmooth V
      rays V == (latticePointList P2)_{0..#rays V-1}
    Text
      This is the simplicial toric variety we want!  Actually, any other
      simplicial toric variety will work too (i.e. any other fine star regular
      triangulation of the point configuration {\tt latticePointList P2}.
    Text
      The Calabi-Yau $X$ is an anti-canonical divisor in $V$ (the same as the
          pull-back of an anti-canonical divisor in $V_0$, which is ample, to $V$
          (the result is no longer ample).
      Batryev (based on Danilov-Khovanskii) has provided formulae for the Hodge numbers
      of such a hypersurface.  The formula for $h^{1,1}(X)$ and $h^{2,1}(X)$, for $X$ 
      the desingularization of a hypersurface in a Fano toric variety of dimension 4, 
      depends only on the polytope.
    Example
      h11OfCY P1
      h21OfCY P1
    Text
      The reflexive polytope is called favorable if $H^{1,1}(X)$ is generated by the
      images of toric divisors on $V$.
    Example
      isFavorable P1
    Text
      Intersection ring of $X$
    Text
      First, let's work on $X$, which is a sufficiently generic hypersurface of $V$
      in the divisor class $|-K_V|$.
    Example
      KV = toricDivisor V
      X = completeIntersection(V, {-KV})
    Text
      The Hodge diamond of $X$, as long as $X$ is sufficiently generic,
      is determined via Danilov-Khovanskii (reference: ...).  However, 
      the following works whenever $X$ is a smooth hypersurface of $V$.
    Example
      hodgeDiamond X
    Text
      Thus $h^{1,1}(X) = 5$ and $h^{1,2}(X) = 57$.
      
      We can do intersection theory on $X$ and $V$.  Note that $V$ is not smooth, but
      since it is simplicial, as long as we work over the rationals, not the integers,
      the intersection ring is well-defined.  Since $X$ is smooth (or assumed to be),
      the intersection ring of $X$ is well-defined.
      
      The way we do all of this is we first create the abstract variety of a point.
      We include some parameters here (we will use them below).  Then, we define
      abstract varieties for $V$ and $X$.  These are designed to work well with the
      intersection theory implemented in Macaulay2 (the package @TO "Schubert2"@).
      An abstract variety contains information about its intersection ring (or, the numerical
      intersection ring), the chern class of its tangent bundle, and how to integrate 
      a cycle on the variety.    
    Example
      pt = base(symbol a, symbol b, symbol c, symbol d, symbol e)
      Va = abstractVariety(V, pt)
      Xa = abstractVariety(X, pt)
      IX = intersectionRing Xa
    Text
      For example, the (restrictions to $X$) of the 9 toric prime divisors:
    Example
      gens IX
      integral(t_2*t_3*t_4)
      integral(t_2^3)
    Text
      The advantage of putting parameters into the base, is that we can generate
      formulas.  For example, the euler characteristic of $L = OO_X(aD_4+bD_5+cD_6+dD_7+eD_8)$
      ($L$ is a line bundle with the given element as first Chern class. Note
      that $D_4, \ldots, D_8$ generate the intersection ring) can be found using
      the following code, which invokes Hirzebruch-Riemann-Roch to find the euler
      characteristic.
    Example
      L = a*t_4 + b*t_5 + c*t_6 + d*t_7 + e*t_8
      F1 = chi OO(L)
      6*(F1-1)
   SeeAlso
///

doc ///
   Key
     hodgeOfCYToricDivisor
     (hodgeOfCYToricDivisor,Polyhedron,List)
   Headline
     compute the cohomology vector of an (irreducible) toric divisor on a CY hypersurface
   Usage
     hodgeOfCYToricDivisor(P,pt)
   Inputs
     P:Polyhedron
       Any polytope will do, although so far it has only been tested on 
       reflexive polytopes.
     pt:List
       a lattice point in the polar dual polytope {\tt polar P}
   Outputs
     :List
       The list of $\{ h^0(X,OO_D), h^1(X,OO_D), h^2(X,OO_D) \}$,
       where $D$ is the intersection of the toric divisor corresponding
       to the lattice point with a hypersurface $X$ corresponding to
       an anti-canonical divisor on the toric 4-fold $V$ corresoponding .
   Description
    Text
      We assume that $P$ is a reflexive 4-dimensional polytope, and let $V_0$ be the 4-dimensional
      toric variety corresponding to $P$ (i.e. corresponding to the normal fan of $P$).  Let $V$
      be a simplicial resolution of $V_0$, corresponding to a star triangulation of the polar dual
      $P^o$, which is fine, i.e. involves all of the lattice points of $P^o$.  Let $X \subset V$ be
      the inverse image of an anti-canonical divisor on $V_0$.  Note that from Batyrev, it turns
      out that $X$ is a smooth Calabi-Yau 3-fold.  Finally, a lattice point $pt$
      of $P^o$ corresponds to a toric divisor on $V$.  Let $D$ be the intersection of this divisor 
      with $X$.
      
      This function computes the vector of cohomologies of the structure sheaf of the surface $D$.
      
      As an example, the following example is taken from the Kreuzer-Skarke database of 4D reflexive 
      polytopes.
      
    Example
       polystr = "Kreuzer-Skarke: 4 12  M:24 12 N:16 11 H:11,19 [-16]
               1   0   0   0   0   1   2   1   0  -2   0  -2
               0   1   0   0   0   0  -2  -1   1   2  -1   0
               0   0   1   0   0  -1   0  -1  -1   1  -1   1
               0   0   0   1  -1   0   1   1  -1   0   1  -2
               "
      A = matrix first kreuzerSkarke polystr
      P = convexHull A
    Text
      This polytope has 12 vertices, 33 edges, 32 2-faces, and 11 facets.
    Example
      # faceList(0,P)
      # faceList(1,P)
      # faceList(2,P)
      # faceList(3,P)
      fVector P
    Text
      
      Note that only the faces which contain interior lattice points, or whose dual does, is included.
      So 6 of the 33 edges of the polytope have an interior vertex along that edge.
      
      There are 15 non-zero lattice points in the dual, meaning that the
      toric 4-fold has 15 toric divisors on it (each is a 3-fold, and also toric).
      It turn out that they all are rigid, in the sense that in each case,
      $h^0(OO_D) = 1$, $h^1(OO_D) = 0$, $h^2(OO_D) = 0$.
    Example
      # latticePointList polar P
      hodgeOfCYToricDivisors P
    Text
      The Hodge numbers $h^{1,1}(X)$ and $h^{2,1}(X)$ can be computed using 
      information about $P$ only, not the specific triangulation used.
    Example
      isFavorable P
      h11OfCY P
      h21OfCY P
   Caveat
     This function currently only works for 4-d reflexive polytopes.  However, the
     formulas work for other dimensions, and these should be included.
   SeeAlso
///

///
  Key
    "computing sheaf cohomology of specific Calabi-Yau hypersurfaces in toric varieties"
  Headline
    facilities available for computing sheaf cohomology
  Description
    Text
    Example
  Caveat
  SeeAlso
    
///

doc ///
  Key
    "facilities available for working with triangulations"
  Headline
    facilities available for working with triangulations
  Description
    Text
      In this introduction, we consider triangulations of the following square
      in the plane.
    Example
      square = transpose matrix{{1,1},{-1,1},{-1,-1},{1,-1}}
      regularFineTriangulation square
      assert(# allTriangulations square == 2)
    Text
      Now consider all of the lattice points of the square.
    Example
      P = convexHull square
      LP = latticePointList P
      sq9 = transpose matrix LP
    Text
      We could have entered sq9 by hand as so:
    Example
      sq9 = matrix {{-1, -1, 1, 1, -1, 0, 0, 1, 0}, 
                    {-1, 1, -1, 1, 0, -1, 1, 0, 0}}
    Text
      We first show some functions from Topcom that are useful.
    Example
      t1 = regularFineTriangulation sq9
      regularTriangulationWeights t1
      fineStarTriangulation(sq9, max t1)
      delaunaySubdivision sq9 -- not a triangulation (4 squares).
      orientedCircuits sq9 -- many of these are not useful when considering only fine triangulations.
    Text
      Let's generate all of the triangulations of the square.
      Really, we want all triangulations which are fine (involve all the lattice points)
      and are star (involve the origin), and are regular.
    Example
      regularFineStarTriangulation sq9 -- leaves out 8, the index of the origin in sq9.
      Ts = allTriangulations sq9;
      #Ts
      Ts = Ts/max;
      # select(Ts, t -> isFine(sq9,t))
      # select(Ts, t -> isStar(sq9,t))
      # select(Ts, t -> isStar(sq9,t) and isFine(sq9,t))
      # select(Ts, t -> isFine(sq9,t) and isRegularTriangulation(sq9,t))
    Text
      Regular triangulations and subdivisions can be computed.
      In this example, we take the first 5 fine triangulations found above,
      find weights (they are all regular triangulations) giving these triangulations,
      then reconstruct the triangulation using @TO regularSubdivision@.
      These are the same as the triangulations we started with.
    Example
      fineT = take(select(Ts, isFine_sq9), 5)
      wts = for t in fineT list regularTriangulationWeights(sq9, t)
      fineT2 = for w in wts list regularSubdivision(sq9, matrix{w})
      fineT == fineT2
    Text
      We might want to check that these are indeed triangulations.
      I am not completely convinced that @TO topcomIsTriangulation@ always gives a
      correct answer, so we also implement a slower routine @TO naiveIsTriangulation@.
    Example
      starT = first select(Ts, t -> isStar(sq9,t))
      naiveIsTriangulation(sq9, starT)
      topcomIsTriangulation(sq9, starT)
      notSq9 = matrix {{-1, -1, 1, 1, -1, 0, 0, 2, 0}, 
                    {-1, 1, -1, 1, 0, -1, 1, 0, 0}}
      naiveIsTriangulation(notSq9, starT)
      topcomIsTriangulation(notSq9, starT)
      debug Triangulations
      isTriangulation(notSq9, starT)
    Text
      All regular triangulations fit into a polytope, whose vertices are the 
      GKZ volume vectors (for each lattice point, consider the sum of the volumes
      of the simplices containing the point as a vertex).  This gives a vector in
      $\Z^d$, where $d$ is the number of lattice points, which is computed by the method
      @TO volumeVector@.
    Example
      volume convexHull sq9
      tri = fineT_0
      for f in tri list volume convexHull(sq9_f)
      sum oo == volume convexHull sq9
      volumeVector(sq9, tri)
      volumeVector(sq9, starT)
    Text
      Sometimes we want to generate only some of the triangulations, as there can be
      a huge number of them.  Unfortunately, the topcom functions do not allow this
      functionality.  Instead, use @TO generateTriangulations@.  Note that this function
      only generates fine triangulations.
    Example
      T4 = generateTriangulations(sq9, Limit => 100);
      T3 = select(Ts, t -> isFine(sq9,t));
      assert(set (T4/max) === set T3)
  SeeAlso
    generateTriangulations
    "Topcom::allTriangulations"
///


///
  Key
    vertexMatrix
  Headline
  Usage
  Inputs
  Outputs
  Consequences
  Description
    Text
    Example
  Caveat
  SeeAlso
///

doc ///
  Key
    "cohomology of line bundles on toric varieties"
  Headline
    introduction to computing line bundle cohomologies in Macaulay2
  Description
    Text
    Example
      topes = kreuzerSkarke(3, Access=>"wget");
      topes_9
      A = matrix topes_11
      P = convexHull A
      P2 = polar P
      V = reflexiveToSimplicialToricVariety P
      S = ring V -- the Cox ring
      GLSM = transpose matrix degrees S
      SR = dual monomialIdeal V
      assert isSimplicial V
      assert isSmooth V
      picardGroup V === ZZ^3
    Text
      As an example, let's compute the cohomology of the line bundle $OO_V(-2,3,-4)$.
    Example
      D = 2*V_1 + 3*V_0 - 4*V_6
      degree D
      for i from 0 to 4 list HH^i(V, OO(D))
      for i from 0 to 4 list rank HH^i(V, OO(D))
      cohomologyVector(V, {-2,3,-4})
      cohomologyVector(V, D)
      hashTable for i from 0 to # rays V - 1 list i => cohomologyVector(V, V_i)
    Text
      @SUBSECTION "Bases of cohomology groups"@
    Text
      We now delve a bit deeper into the bases of these cohomology groups.
      
      There are a number of pointed orthants in $\ZZ^n$, where $n$ is the number of rays,
      which support cohomology.
    Example
      netList toricOrthants V
      cohomologyBasis(1, V, {2, 1, 0})
      HH^1(V, OO_V(2,1,0))
      for i from 0 to 3 list cohomologyBasis(i, V, {2, 1, 0})
      for i from 0 to 3 list rank HH^i(V, OO_V(2, 1, 0))
      
      for i from 0 to 3 list cohomologyBasis(i, V, {2, 1, -2})
      for i from 0 to 3 list cohomologyBasis(i, V, {2, 1, -3})
    Text
      @SUBSECTION "Cohomology on Calabi-Yau hypersurfaces"@
    Text
  SeeAlso
///

------------------------------------------------
-- Database creation and retrieval functions ---
------------------------------------------------
doc ///
  Key
    (createCYDatabase, String, List)
    createCYDatabase
  Headline
    create a database file and populate it with CYPolytope's
  Usage
    createCYDatabase(filename, topes)
  Inputs
    filename:String
      the desired name of the data base file.  If the file doesn't exist it is created,
      otherwise the name should be the name of an existing data base file, and this file
      is modified
    topes:List
      of @ofClass KSEntry@'s, a list of Kreuzer-Skarke type entries for some polytopes
  Consequences
    Item
      For each polytope corresponding to an entry in the {\tt topes} list, 
      a @ofClass CYPolytopeData@ is created, and various information about it is computed
      and then stored in the data base file for later use
  Description
    Text
      A CYDatabase file is a database file whose contents are precomputed data
      about some @TO CYPolytopeData@'s and @TO CYData@'s.  Since some information takes
      non-trivial time to construct, we precompute this data, and then we can later pull up
      this data via the functions @TO readCYDatabase@, @TO "readCYPolytopes"@, and @TO readCYs@.
    Text
      The CYPolytope corresponding to each item of the {\tt topes} list is constructed
      and some basic data is computed (e.g. information about the faces of the polytopes, whether the
      polytope is favorable, and degree information about it.  This data is then stored in the
      database for later retrieval.
    Example
      filename = "foo-remove-me.dbm"
      if fileExists filename then removeFile filename
      topes = kreuzerSkarke(2, Limit => 3)
      createCYDatabase(filename, topes)
    Example
      F = openDatabase filename
      F#"1"
      V = cyPolytopeData F#"1"
      hh^(1,1) V
      hh^(1,2) V
      isFavorable V
    Text
      As a data base file, all keys of {\tt F} are strings, and the values are strings too.
    Example
      sort keys F
    Text
      Close the database file when done with it.
    Example 
      close F
    Text
      For this example, we also delete this database file.
    Example
      removeFile filename
  SeeAlso
    addToCYDatabase
    readCYDatabase
    readCYs
///

--     (addToCYDatabase, String, Database, ZZ) do we want this one?
///
  Key
    addToCYDatabase
    (addToCYDatabase, String, CYPolytopeData)
  Headline
    add data for every Calabi-Yau hypersurface coming from a given (reflexive) CYPolytopeData
  Usage
    addToCYDatabase(filename, Q)
  Inputs
    Q:CYPolytopeData
  Consequences
    Item
      Data for all triangulations, or all 2-face inequivalent triangulations is placed into 
      the database with file name {\tt filename}
  Description
    Text
    Example
      filename = "foo-remove-me.dbm"
      if fileExists filename then removeFile filename
      topes = kreuzerSkarke(2, Limit => 3)
      createCYDatabase(filename, topes)
    Text
    Example
      Qs = readCYPolytopes(filename)
      addToCYDatabase(filename, Qs#0, NTFE => true)
      addToCYDatabase(filename, Qs#1, NTFE => true)
      addToCYDatabase(filename, Qs#2, NTFE => true)
      readCYs(filename, Qs)
      R = ZZ[x,y]
      (Qs, Xs) = readCYDatabase(filename, Ring => R)
      Qs
      Xs
      
      R = ZZ[a,b,c,d]
      (Qs, Xs) = readCYDatabase("./m2-examples/cys-ntfe-h11-4-h12-100.dbm", Ring => R);
  SeeAlso
///

///
  Key
  Headline
  Usage
  Inputs
  Outputs
  Consequences
    Item
  Description
    Text
    Example
  SeeAlso
///



///
-*
  restart
  needsPackage "StringTorics"
*-
  topes = kreuzerSkarke(5, Limit=>10, Access=>"wget")

  A = matrix topes_9
  P = convexHull A
  P2 = polar P
  LP = matrix{latticePoints P2}
  elems2 = regularSubdivision(LP, matrix{{1/2, 1/10, 10, 3, 2, 8, 12, 7/8, 9/11, 1}})
  hts = for i from 0 to numcols LP-1 list random 100
  elems3 = regularSubdivision(LP, matrix{hts})
  elems = regularFineTriangulation LP
  for e in elems list latticeVolume convexHull LP_e
  for e in elems2 list latticeVolume convexHull LP_e
  sum for e in elems3 list latticeVolume convexHull LP_e
  sort unique flatten elems == toList(0..numcols LP-1)
  sort unique flatten elems2 == toList(0..numcols LP-1)
  sort unique flatten elems3 == toList(0..numcols LP-1)
  -- I would like to check that these are well-defined triangulations
  latticeVolume P
  latticeVolume P2
  
  vertices P -- matrix over QQ
  vertexList P -- list (over ZZ or QQ?), different order than 'vertices'
  vertexMatrix P
  faceList
  faceDimensionHash
  minimalFace
  latticePoints P -- list of single column matrices, over ZZ
  latticePointList P
  latticePointHash
  interiorLatticePoints
  interiorLatticePointList
  faces(3,P)
  faceList(1,P)
  vertices P2
  matrix{latticePoints P2}
  
///

///
-*
  restart
  needsPackage "StringTorics"
*-
  topes = kreuzerSkarke(80, Limit=>10, Access=>"wget")
  A = matrix topes_9
  P = convexHull A
  P2 = polar P
  vertices P -- matrix over QQ
  vertexList P -- list (over ZZ or QQ?), different order than 'vertices'
  vertexMatrix P
  faceList
  faceDimensionHash
  minimalFace
  latticePoints P -- list of single column matrices, over ZZ
  latticePointList P
  latticePointHash
  interiorLatticePoints
  interiorLatticePointList
  faces(3,P)
  faceList(1,P)
  vertices P2
  matrix{latticePoints P2}
  
///

-*
///
  Key
  Headline
  Usage
  Inputs
  Outputs
  Consequences
  Description
    Text
    Example
  Caveat
  SeeAlso
///
*-

