---------------------------------------
-- gvInvariants
-- Gopakumar-Vafa invariants (similar to Gromov-Witten invariants)
-- Contains code to call the external C++ program `computeGV` from CYTools
-- This requires computing some information first (intersection numbers, mori cone cap, etc).
---------------------------------------

GVTable = new Type of HashTable
expression GVTable := GVT -> expression GVT.GVs
net GVTable := GVT -> (
    v := for c in GVT.GVs list {c#0, dotProduct(c#0, GVT.Heft), c#1};
    netList(prepend({"Curve", "Degree", "GV"}, v), Boxes => false, HorizontalSpace => 1)
    )

heft GVTable := List =>  GVT -> GVT.Heft

degreeLimit = method()
degreeLimit GVTable := GVT -> GVT.DegreeLimit

GVRayTable = new Type of BasicList -- keys: curve classes, values: {degree, ray of GV values}
net GVRayTable := gvrays -> (
    x := for x in gvrays list {x#0, x#1#0, x#1#1};
    netList(prepend({"Curve", "Degree", "GV"}, x), Boxes => false, HorizontalSpace => 1)
    )

toricMoriCone(NormalToricVariety, List) := Cone => (V, basisIndices) -> (
    IV := intersectionRing (abstractVariety V);
    Cs := matrix for x in orbits(V, 1) list (
        c := product(x, i -> IV_i);
        for j in basisIndices list integral(c * IV_j)
        );
    posHull transpose lift(Cs, QQ) -- TODO: lift to ZZ?
    )

toricMoriCone CalabiYauInToric := Cone => X -> (
    -- TODO: handle toric mori cones of non-favorables
    if isFavorable X then toricMoriCone(ambient X, basisIndices X)
    )

hilbertBasisGenerators = method()
hilbertBasisGenerators Cone := List => C -> (
    for x in hilbertBasis C list flatten entries x
    )

-- This function returns a very large heft vector.  Not so good!
-- TODO: this appears to be computing the toricMoriCone, which it is not using!?
heft CalabiYauInToric := List => X -> (
    C := toricMoriCone X;
    heft1 := sum entries transpose rays dualCone C;
    Ccap := posHull transpose matrix toricMoriConeCap X;
    heft2 := sum entries transpose rays dualCone Ccap;
    heft2
    )

----------------------------
-- new code May 2026 -------
----------------------------

gvInvariants = method(Options => {
    Mori => null, -- null means: compute rays of the Mori cone of V (in ZZ^(h11))
    Heft => null, -- null means: compute it
    DegreeLimit => infinity, -- TODO: what to do if not given??
    Precision => 150
    })

encodeArrayArrayInt = method()
encodeArrayArrayInt List := List => L -> (
    parts := flatten for i from 0 to #L - 1 list prepend(#L#i, L#i);
    prepend(#L, parts))

gvInvariants0 = method(Options => options gvInvariants)
gvInvariants0(List, List, List, List) := opts -> (mori, heftvec, glsm, intersectionnums) -> (
    gvs := rawGVInvariants(
        encodeArrayArrayInt mori,
        encodeArrayArrayInt {},
        heftvec,
        encodeArrayArrayInt glsm,
        encodeArrayArrayInt {}, -- nefpart
        encodeArrayArrayInt intersectionnums,
        {opts.DegreeLimit, opts.Precision, 0, 300000}
        );
    e := entries transpose map(ZZ, gvs);
    gvs = for r in e list drop(r, -1) => r#-1;
    GVT := new GVTable from {
        cache => new CacheTable,
        GVs => gvs,
        Heft => heftvec,
        DegreeLimit => opts.DegreeLimit,
        MoriConeCap => mori -- Hilbert basis of a cone containing the Mori cone of the CY hypersurface.
        };
    rays GVT; -- sets rays stuff, TODO: don't do this?
    GVT
    )

rays GVTable := {} >> opts -> GVT -> (
    -- make the rays.  Each entry is a {curve class, degree, list of gvs for curve, 2*curve, etc}
    -- this is ordered: in order generated by the computeGV function in c++.
    GVT.cache.rays ??= (
        deglimit := GVT.DegreeLimit;
        degvector := GVT.Heft;
        primcurve := curve -> (
            i := position(curve, a -> a != 0);
            c := curve // gcd curve;
            mult := curve#i // c#i;
            {c, mult}
            );
        -- curves is a list of {primitive curve, mult, GV}.
        curves := for k in GVT.GVs list join(primcurve k#0, {k#1});
        H := partition(val -> val#0, curves);
        -- H2 is a hash table of (primitive clurve class) => list of {prim curve, mult, GV}.
        H2 := hashTable for kv in pairs H list (
            val := kv#0 => kv#1/(x -> {x#1, x#2});
            val); 
        -- now we change the values to be a list of gv's.
        toRayList := (primcurve, listOfPairs) -> (
            Hmult2gv := hashTable listOfPairs;
            d := max (listOfPairs/first);
            deg := dotProduct(degvector, primcurve);
            maxmult := max(d, deglimit//deg);
            for i from 1 to maxmult list if Hmult2gv#?i then Hmult2gv#i else 0
            );
        result := hashTable for kv in pairs H2 list (
            val := toRayList(kv#0, kv#1);
            kv#0 => val
            --if #val >= 2 then kv#0 => val else continue -- this misses curves that we might need for mori cone!
            );
        -- now we massage the data a bit (sort them by increasing heft degree, and place that in the lists.
        result = sort for c in keys result list {dotProduct(c, degvector), c, result#c};
        result = for k in result list {k#1, k#0, k#2};
        result
        )
    )

gvInvariants(NormalToricVariety, List) := GVTable => opts -> (V, basisIndices) -> (
    -- TODO: check favorability??
    intersectionnums := for t in intersectionNumbersOfCY(V, basisIndices) list append(t#0, t#1);
    mori := if opts.Mori =!= null then 
                opts.Mori 
            else 
                hilbertBasisGenerators toricMoriCone(V, basisIndices); -- list of curve classes
    heft := if opts.Heft =!= null then opts.Heft else (
        sum entries transpose rays dualCone posHull transpose matrix mori
        );
    glsm := transpose degrees ring V; -- requires no torsion in class group?
    if not instance(opts.DegreeLimit, ZZ) then error "expected integer DegreeLimit";
    gvInvariants0(mori, heft, glsm, intersectionnums, opts)
    )

gvInvariants CalabiYauInToric := GVTable => opts -> X -> (
    if not isFavorable X then return null;
    intersectionnums := for t in intersectionNumbers X list append(t#0, t#1);
    mori := if opts.Mori =!= null then 
                opts.Mori 
            else 
                hilbertBasisGenerators posHull transpose matrix toricMoriConeCap X;
    heft := if opts.Heft =!= null then opts.Heft else (
        sum entries transpose rays dualCone posHull transpose matrix mori
        ); -- TODO: if opts.Heft =!= null, check it for correctness?
    glsm := transpose degrees X; -- requires no torsion in class group?
    if not instance(opts.DegreeLimit, ZZ) then error "expected integer DegreeLimit";
    gvInvariants0(mori, heft, glsm, intersectionnums, opts)
    )

displayRays = method(Options => {"OneOnly" => false})
displayRays GVTable := opts -> GVT -> (
    v := rays GVT;
    if opts#"OneOnly" then v = select(v, x -> #x#2 >= 2);
    netList(prepend({"Curve", "Degree", "GV"}, v), Boxes => false, HorizontalSpace => 1)
    )

gvRayTable = method()
gvRayTable GVTable := GVRayTable => (GVT) -> (
    GVT.cache.GVRayTable ??= new GVRayTable from for x in rays GVT list x#0 => {x#1, x#2}
    )

gvRayTable(GVTable, Set) := GVRayTable => (GVT, negatedCurveSet) -> (
    if # negatedCurveSet === 0 then return gvRayTable GVT;
    H := gvRayTable GVT;
    new GVRayTable from for x in H list if member(x#0, negatedCurveSet) then {-x#0, x#1} else x
    )

-- Create the GV cone: want the extremal rays of the cone of all curve classes so far found that
-- have non-zero GV.
gvCone = method(Options => options gvInvariants)
-- gvCone GVTable := opts -> GVT -> (
--     -- take1/2 or 1/4 of degree bound.  Compute cone.  If it lies on a hyperplane,
--     -- continue to larger size.
--     -- Let C be this cone.
--     -- for the rest of the curve classes (with higher degree), select the ones
--     -- that are not in C.
--     -- then create the new cone, returning either the cone, or a matrix whose columns are the
--     -- extremal elements of the cone.

--     deglimit := degreeLimit GVT;
--     curves := GVT.cache.rays/first;
--     -- step 1.  Determine the degree to start with, then double the degree each time.
--     -- TODO: need to choose deg so that C is full dimensional, OR, use hyperplanes C below too
--     --  (the latter is probably best).
--     deg := ceiling((degreeLimit GVT)/4);
--     curveMatrix := transpose matrix curves;
--     currentcurves := positions(GVT.cache.rays, x -> x#1 <= deg); -- positions, not curves
--     C := posHull curveMatrix_currentcurves;
--     H := halfspaces C;
--     -- warning: still should consider hyperplanes C...
--     remaining := positions(entries transpose matrix(H * curveMatrix), c -> any(c, a -> a < 0));
--     while #remaining > 0 do (
--         curveMatrix = curveMatrix_remaining;
--         C = posHull((rays C) | curveMatrix);
--         H = halfspaces C;
--         remaining = positions(entries transpose matrix(H * curveMatrix), c -> any(c, a -> a < 0));
--         deg = deg*2;
--         );
--     --GVT.cache.gvCone = entries transpose rays C;
--     C
--     )
gvCone(GVRayTable, ZZ) := Cone => opts -> (gvr, deglimit) -> (
    -- gvr is the result of gvRayTable(GVT, negatedCurveSet) or gvRayTable GVT.
    -- deglimit is degreeLimit GVT.
    curves := for x in gvr list x#0; -- these are already negated for "negated curves".
    deg := ceiling((deglimit)/4);
    curveMatrix := transpose matrix curves; -- CHANGE THIS LINE to include negated curves
    currentcurves := positions(toList gvr, x -> x#1#0 <= deg); -- positions, not curves
    C := posHull curveMatrix_currentcurves;
    H := halfspaces C;
    -- warning: still should consider hyperplanes C...
    remaining := positions(entries transpose matrix(H * curveMatrix), c -> any(c, a -> a < 0));
    while #remaining > 0 do (
        curveMatrix = curveMatrix_remaining;
        C = posHull((rays C) | curveMatrix);
        H = halfspaces C;
        remaining = positions(entries transpose matrix(H * curveMatrix), c -> any(c, a -> a < 0));
        deg = deg*2;
        );
    C
    )
gvCone(GVTable, Set) := opts -> (GVT, negatedCurveSet) -> ( -- TODO: ops to be used where?
    gvr := gvRayTable(GVT, negatedCurveSet);
    gvCone(gvr, degreeLimit GVT)
    )
gvCone GVTable := Cone => opts -> GVT -> gvCone(gvRayTable GVT, degreeLimit GVT, opts)

partitionGVConeByGV = method(Options => options gvInvariants)
-- partitionGVConeByGV CalabiYauInToric := HashTable => opts -> X -> (
--     -- return null if we cannot computr GV invariants (i.e. if non-favorable).
--     GVT := gvInvariants(X, opts);
--     if GVT === null then return null;
--     H := extremalCurves GVT;
--     minngv := min for c in keys H list #H#c#2;
--     partition(c -> take(H#c#2, minngv), keys H)
--     )
partitionGVConeByGV CalabiYauInToric := HashTable => opts -> X -> (
    -- return null if we cannot computr GV invariants (i.e. if non-favorable).
    GVT := gvInvariants(X, opts);
    if GVT === null then return null;
    gv := hashTable GVT.GVs; -- hash table: curve => value
    C := posHull transpose matrix (keys gv);
    gvX := entries transpose rays C;
    partition(f -> gv#f ?? 0, gvX)
    )

-- local function, I think?
classifyExtremalCurveClass = method()
classifyExtremalCurveClass List := rayC -> (
    -- rayC: a list of the gv invariants along the ray of a toric mori cone extremal curve.
    -- these are either extremal on the CY, or not effective on the CY.
    if #rayC <= 2 then return "OTHER";
    if all(2..#rayC-1, i -> rayC#i == 0) then (
        -- only first two, possibly, are non-zero.
        if rayC#0 == 0 and rayC#1 == 0 then return "ZERO";
        if rayC#0 == -2 or rayC#1 == -2 then return "TYPEIII0";
        if rayC#0 >= 0 and rayC#1 >= 0 then return "FLOP"; -- these could be type IIIg as well?
        if rayC#0 < 0 or rayC#1 < 0 then return "TYPEIIIg";
        )
    else return "TYPEII"
    )

extremalCurves = method(Options => {Limit => 4, Heft => null})
-- extremalCurves GVTable := opts -> GVT -> (
--     -- TODO? stash extremal curves, and their GV rays (at least first 4 values).
--     -- can recreate the degrees, and also the classification, but keep: extremal curve => gvray values.
--     if opts.Heft =!= null then error "this version cannot use a degree function";
--     H := new HashTable from for x in rays GVT list x#0 => {x#1, x#2};
--     E := entries transpose rays gvCone GVT;
--     extremals := for c in E list (
--         rayC := H#c#1; -- list of GV invariants along ray of c.
--         typ := classifyExtremalCurveClass rayC;
--         c => {H#c#0, typ, take(H#c#1, opts.Limit)} -- take a max of opts.Limit values for each ray
--         );
--     hashTable extremals
--     )
extremalCurves(GVRayTable, ZZ) := HashTable => opts -> (GVR, deglimit) -> (
    -- result is a hashtable of:
    -- (curve class) => {degree, type, GV list along ray}
    if opts.Heft =!= null then error "this version cannot use a degree function";
    H := hashTable GVR;
    E := entries transpose rays gvCone(GVR, deglimit);
    extremals := for c in E list (
        rayC := H#c#1; -- list of GV invariants along ray of c.
        typ := classifyExtremalCurveClass rayC;
        c => {H#c#0, typ, take(H#c#1, opts.Limit)} -- take a max of opts.Limit values for each ray
        );
    hashTable extremals
    )
extremalCurves(GVTable, Set) := HashTable => opts -> (GVT, negatedCurveSet) -> (
    GVR := gvRayTable(GVT, negatedCurveSet);
    deglimit := degreeLimit GVT;
    extremalCurves(GVR, deglimit)
    )

-*
-- WORKING ON THIS
    -- result is a hashtable of:
    -- (curve class) => {degree, type, GV list along ray}
    if opts.Heft =!= null then error "this version cannot use a degree function";
    gvr := gvRayTable(GVT, negatedCurveSet);
    H := hashTable gvr;
    --H := gvRayTable(GVT, negatedCurveSet);
    -- H := new HashTable from for x in rays GVT list x#0 => {x#1, x#2};
    E := entries transpose rays gvCone(gvr, degreeLimit GVT);
    extremals := for c in E list (
        rayC := H#c#1; -- list of GV invariants along ray of c.
        typ := classifyExtremalCurveClass rayC;
        c => {H#c#0, typ, take(H#c#1, opts.Limit)} -- take a max of opts.Limit values for each ray
        );
    hashTable extremals
    )
*-

extremalCurves GVTable := HashTable => opts -> GVT -> extremalCurves(GVT, set{}, opts)

-- Keep this, but we will need to change its name (Jun 13)
-- The following requires the extremal curves, fills in the GV info for these classes.
extremalCurves(CalabiYauInToric, List) := opts -> (X, curveClasses) -> (
    if not isFavorable X then return null; -- later, maybe we can modify this...
    degvec := if opts.Heft =!= null then opts.Heft else heft X;
    hashTable for curveClass in curveClasses list (
        degC := dotProduct(degvec, curveClass);
        deglimit := opts.Limit * degC;
        GVT := gvInvariants(X,Mori => {curveClass}, DegreeLimit => deglimit, Heft => degvec);
        gvHash := hashTable GVT.GVs;
        rayC := for i from 1 to opts.Limit list (
            c := i * curveClass;
            if gvHash#?c then gvHash#c else 0
            );
        typ := classifyExtremalCurveClass rayC;
        curveClass => {degC, typ, rayC}
        )
    )

nilpotentCurves = method()
nilpotentCurves GVRayTable := GVR -> (
  for x in GVR list (
      thisray := x#1#1;
      if (#thisray >= 4 and thisray#-1 == 0 and thisray#-2 == 0 )
      or (#thisray <= 3 and thisray#-1 == 0)
      then {x#0, x#1#0, take(x#1#1, 4)}  else continue
      )
  )

flopCurves = method()
flopCurves GVRayTable := GVR -> (
    error "not implemented yet"
    )

-- Also stash the value?  Yes!
-- gvCone CalabiYauInToric := Cone => opts -> X -> (
--     if not isFavorable X then return null;
--     gv := gvInvariants(X, opts);
--     if gv === null then return null;
--     posHull transpose matrix ((keys gv)/toList)
--     )

-- also partition the extremal curve classes by first 2 values of the gv ray?

moriCone = method()
moriCone(GVTable, Set) := Cone => (gvTable, negatedCurveSet) -> (
    -- We take the primitive curves in the table, negate the ones that need negating,
    -- and make the cone of all these
    gvr := gvRayTable(gvTable, negatedCurveSet);
    curves := transpose matrix for x in gvr list x#0;
    posHull curves
    )
moriCone GVTable := Cone => gvTable -> moriCone(gvTable, set{})

------------------------------
-- end of new code May 2026 --
------------------------------

end--

-- Database-dependent GV tests and scratch code moved to ScratchGVInvariants.m2
